version: "3.8"

services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8086:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: on-failure
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: godel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
     