server:
  port: 8086

spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    database: mysql
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
  liquibase:
    change-log: 'classpath:db.changelog-master.xml'
  datasource:
    url: 'jdbc:mysql://localhost:3306/godel?createDatabaseIfNotExist=true'
    username: root
    password: root